name: Merge Branches

on:
  workflow_dispatch:
    inputs:
      branches:
        description: '머지할 브랜치를 쉼표로 구분하여 입력하세요.'
        required: true
      target_branch:
        description: '타겟 브랜치를 입력하세요.'
        required: true

jobs:
  merge_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.name "${{ secrets.GITHUB_USER }}"
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"

      - name: Create target branch
        run: |
          git checkout -b ${{ github.event.inputs.target_branch }} develop
          git push -u origin ${{ github.event.inputs.target_branch }}

      - name: Debug - Show branch information
        run: |
          git branch -a
          git log --oneline --decorate --graph --all

      - name: Debug - Show target branch status
        run: |
          git checkout ${{ github.event.inputs.target_branch }}
          git status

      - name: Merge branches
        run: |
          git checkout ${{ github.event.inputs.target_branch }}
          IFS=',' read -ra branches <<< "${{ github.event.inputs.branches }}"
          for branch in "${branches[@]}"; do
            git merge --no-ff $branch || exit 1
          done
          git push origin ${{ github.event.inputs.target_branch }}
